#!/bin/bash

echo "syncing files from 'synced'"
rsync \
    -avzPm \
    --include="*/" \
    --include-from='synced' \
    --exclude="*" \
    $HOME/.[^.]* .

echo "syncing files from 'scripts'"
rsync -avzPm $HOME/scripts .

# .pyenv/.vimrc syncs due to .vimrc on synced file
rm -rf .pyenv

# --include="*/"            => include all subdirectories
# --include-from='synced'   => include all specific patterns
# --exclude="*"             => exclude all the rest
