#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# desktop
bspc monitor HDMI-1 -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52

bspc rule -a Chromium state=pseudo_tiled

if [ -x /usr/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh &
fi

if [ -d $HOME/wallpapers ]; then
    feh --bg-center $(find $HOME/wallpapers -type f | shuf -n 1)
fi
