#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# laptop
bspc monitor eDP-1-1 -d V VI VII VIII
# external monitor
bspc monitor HDMI-1-1 -d I II III IV

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [ -x /usr/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh &
fi

if [ -d $HOME/wallpapers ]; then
    feh --bg-center $(find $HOME/wallpapers -type f | shuf -n 1)
fi
